### ISSUE TITLE
WiNet-S2 automatic logout prompt ends login session in proportion to polling frequency

### ISSUE THREAD

**Issue by AuThomasPrime** [NickStallman/home-assistant-repo#14]
When the WiNet extractor addon is running, the WiNet-S2 web portal will constantly present you with an automatic logout prompt as frequently as the set polling interval. This makes the web portal unusable at low polling intervals (e.g. <= 10 seconds). I need to turn off the addon if I want to use the web portal effectively.

![image](https://github.com/user-attachments/assets/560b7ac8-85d2-4f2e-978a-990879795f13)

**Comment by wangeris** [comment]
I'm getting the same, but I believe it's a limitation of the WiNet adapter permitting singular connection (due to limited resources) rather than a problem with WiNet extractor itself.

**Comment by AuThomasPrime** [comment]
That makes sense. If it's not causing any other issues then I think it's a small price to pay for having access to the data in Home Assistant. Once setup, the web portal isn't something you really need to access frequently anyway.

**Comment by NickStallman** [comment]
Yep this effect is expected with the newest firmware. The Winet only wants one user accessing it at a time essentially.
Earlier firmware may have allowed it, but it did cause some rather unpredictable behaviour which is probably why they put the restriction in.

I find myself very rarely needing the UI, and when I do I just stop the addon then start it again once I'm done.

I don't believe there's any possible bypass, and certainly not a stable one.
