### ISSUE TITLE
Missing change log entry for 0.1.9

### ISSUE THREAD

**Issue by yelhsa083** [NickStallman/home-assistant-repo#16]
Appears the latest version is 0.1.9
There is no notice of the improvement/s or changes actioned between 0.1.8 to 0.1.9

Would like to confirm changes before updating 

Thanks

**Comment by NickStallman** [comment]
Oh I must have forgotten to commit the changelog entry. Whoops.

The main difference was adding better support for running it standalone not as a Home Assistant addon.
You can see the full changes here: https://github.com/NickStallman/home-assistant-repo/commit/6761aa550757099f15cd0e9e6bfaa365fd9397b7#diff-03a4bec8cce9153b099943b4a56463b3045ff51db927f57b4be6ff1d1d51ae43
