### ISSUE TITLE
Mqtt wrong - tried several formats but nothing works

### ISSUE THREAD

**Issue by cryd-s** [NickStallman/home-assistant-repo#17]
![image](https://github.com/user-attachments/assets/cee1722f-dc5f-45e1-9a9f-0dd4454ea7f0)

I tried:

mqtt://mqttuser:"topsecret#001"@192.168.1.10:1883
mqttuser:"topsecret#001"@192.168.1.10:1883
mqtt://mqttuser:"topsecret#001"@192.168.1.10
mqttuser:"topsecret#001"@192.168.1.10

**Comment by cryd-s** [comment]
the credentials are correct

**Comment by 42asdf** [comment]
I think you cannot give username and password in the mqtt URL. I implemented options to give the MQTT username and password for #18  and opened a pull request.

**Comment by NickStallman** [comment]
@cryd-s I wonder if you have any special characters in your password which may be throwing it off?

getaddrinfo is trying to resolve mqttuser which is of course not right.
The format ```mqtt://<username>:<password>@<host>``` works well for me, however my password is very long and  doesn't include any symbols.

**Comment by 42asdf** [comment]
If you have special characters in your password, you can try encoding them e.g. using the following python code:
```
import urllib.parse
password = "a%€$"
print(urllib.parse.quote(password, safe=''))
```

**Comment by NickStallman** [comment]
Yep a urlencode will sort out any complex passwords, an easy approach is a online tool like https://www.urlencoder.org/
