### ISSUE TITLE
Mqtt address

### ISSUE THREAD

**Issue by SNAPE15** [NickStallman/home-assistant-repo#2]
Thanks for the addon, hopefully its a sucess. I'm having an issue with connection to mqtt (mosquitto). I see the address format your using, but as far as using mqtt addressing before Ive only used core-mosquitto. Only used mqtt for GoSungrow before so not experienced in it. Do I need to setup a username and password for this addon to work?

**Comment by yelhsa083** [comment]
I found the same, but then saw the descriptor (which now seems to have less detail) User and PW go in the mqtt server line, along with specified port at the end.

mqtt://user:pass@ipaddress:1883
Port assumed to be 1883

**Comment by SNAPE15** [comment]
> I found the same, but then saw the descriptor (which now seems to have less detail) User and PW go in the mqtt server line, along with specified port at the end.
> 
> mqtt://user:pass@ipaddress:1883 Port assumed to be 1883

 I knew that mqtt address, but ive never had/created/used a user/pass for mqtt, so asking do I actually need to create that for it to work

**Comment by yelhsa083** [comment]
I think you do

Go to mosquito mqtt server
Config
In the options segment there is logins with a typable area

Add to the below to that area and save

`- username: goodusername
  password: goodpassword`

**Comment by SNAPE15** [comment]
> I think you do
> 
> Go to mosquito mqtt server Config In the options segment there is logins with a typable area
> 
> Add to the below to that area and save `- username: goodusername` `password: goodpassword`
> 
> Just make sure the alignment has username and password aligned Cannot seem to get it correctly shown here

thanks, got it working. yes, needs that format exact.

now to play....

**Comment by NickStallman** [comment]
Let me know how you go. :)

Quite a few addons use MQTT so I didn't provide the exact instructions for setting it up.

MQTT could be anonymous without a login in which case mqtt://hostname should work skipping the user:pass@ bit.
I just realised my example in the README appears to be stuffed so I'll double check why that happened.

**Comment by NickStallman** [comment]
If everything is going well with this, I'll close this ticket.
The docs should be slightly clearer now on the mqtt url format.

**Comment by SNAPE15** [comment]
So far yes, all good. Havent played too much yet.
