### ISSUE TITLE
Template variable warning: 'dict object' has no attribute 'value' when rendering '{{ value_json.value }}'.

### ISSUE THREAD

**Issue by pguest80** [NickStallman/home-assistant-repo#35]
Is it possible that the MQTT broker is causing this warning in Home Assistant?

Logger: homeassistant.helpers.template
Source: helpers/template.py:2748
First occurred: 18:18:02 (486 occurrences)
Last logged: 19:43:06

Warning: Template variable warning: 'dict object' has no attribute 'value' when rendering '{{ value_json.value }}'.

I get the warnings exactly when 30 sensors are updated according to the extractor. This happens approximately every 5 minutes.

How can I avoid this if it is, or can I safely ignore it? It generates several thousand warnings per day.

**Comment by Leahcim70** [comment]
@pguest80 is it possible that you just try to access a wrong value in a template?

**Comment by NickStallman** [comment]
Yep this addon doesn't use templates, so it's something you've got referencing the Winet values.

**Comment by MeierAlex** [comment]
Hallo,

I have exactely the same problem like described in the initial post. I use some entities for my energy monitoring dashboard - could this be the cause for the errors ?

**Comment by Leahcim70** [comment]
> Hallo,
> 
> I have exactely the same problem like described in the initial post. I use some entities for my energy monitoring dashboard - could this be the cause for the errors ?

You are using a non existent entity in your dashboard.
