### ISSUE TITLE
daily_purchased_energy unknown

### ISSUE THREAD

**Issue by SNAPE15** [NickStallman/home-assistant-repo#6]
anyone got Grid Consumption: daily_purchased_energy working? Mine is just showing as unknown.

Also getting unknown for daily_feed_in_energy

**Comment by NickStallman** [comment]
Yep on my SH10RS a bunch of those fields are unknown.

I'm guessing that those values are populated on some inverters and not others, it's like all the issues with Modbus where different inverters have different data in different registers, and this related to that.
You'll notice when going to the Winet web interface directly you don't get those values there, so it's not a bug in the addon.

What I do is create some integration templates like what the Readme has for mppt1/2/3/4 energy, and calculate the values from the power values.
All the power values are present and accurate (for the SH10RS at least) so Home Assistant can handle calculating the energy.
